# Generated by Django 2.2 on 2020-08-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_posted',
        ),
    ]
